dist: trusty
sudo: required
language: bash
before_install:
- if [ "$TRAVIS_BRANCH" = "master" ]; then sh ./play-travis/requirements.sh; fi
- if [ "$TRAVIS_BRANCH" = "master" ]; then sh ./play-travis/test.sh; fi
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: SP2i3VaclwuXDC+ef9hGPJQxcOKIQMc1qKSTIOuT0edGe7gmfx7cOUdI+9zfmCYwNWUMVFyyT840w22Pw0p0jMZ6W3tZFl5t615LJnLlkxSUr+ZWrodVSmwwB86EGz0gpPlxfZAmMPkreJ0Vnt/iEJxaUynnkPGFC3TZ44Xa/F//rWmBn+b5Lhwty253jrT3zAEvAs50s0UHOHH3UmZJqwSiPqeY83xK4tx7O/nWn59vl48TytkvRs7+uzFn6+GtVSn7+x1cgWf7SCBm/RLWsq7oqjosNYuzsCawwCuvbQtbfo+tdi6zIx4YXU2wHaDO2B2SS3cfnU89JL8LDssU8fZaWAZFMh4l4s/NUIynbCapO0rqj3zQZcaS2zWs2jCf/y0KczPapSBiNacFmrtWmTUagi1H3eCdtZxjrY91KAD1w/LmtHgFb3Uptm7iSDW5zp6hkes3+XofOEg791ZR8hVlkefEXowKFWQXgBkjMZdzxFxjyT360lxnfgae5gtFkYAqZTRrsnjo6FK7FD4G9Lp1QmyTAEFgZ/NAJtp8DKOq2LIdb+OVMadAE9zdf3agr1BQLb94CKNBStTqnQr9Aj18naY7pGFf7yrcApP12Vf5bi3AJEPVK5hHCzk5cjBnLl6LuO7XsBSm1IvaQ0vwGQQAN347w8wLymeZz7MS0VY=
