- name: Configure app hosts
  hosts: app
  become: true
  vars:
    db_host: "{{ hostvars['reddit-db'].internal_ip }}"
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service

    - name: Add config file for Puma
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      notify: reload puma

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      service: name=puma state=restarted

